let mapleader = "\<Space>"
nnoremap <Leader>w :w<CR>

vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P

nmap <Leader><Leader> V

nmap <Leader>np :set paste<CR>
nmap <Leader>nop :set nopaste<CR>

vnoremap <silent> s //e<C-r>=&selection=='exclusive'?'+1':''<CR><CR>
    \:<C-u>call histdel('search',-1)<Bar>let @/=histget('search',-1)<CR>gv
omap s :normal vs<CR>

map q: :q
if &compatible
  set nocompatible
endif
set runtimepath+=~/.vim/bundles/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.vim/bundles')
  call dein#begin('~/.vim/bundles')

  call dein#add('Shougo/neocomplete.vim')
  call dein#add('junegunn/fzf', { 'build': './install --all', 'merged': 0 })
  call dein#add('junegunn/fzf.vim', { 'depends': 'fzf' })
  call dein#add('scrooloose/nerdtree', { 'on_cmd': 'NERDTreeToggle' })
  call dein#add('ervandew/supertab')
  call dein#add('wincent/command-t')
  call dein#add('terryma/vim-expand-region')
  call dein#add('tpope/vim-commentary')
  call dein#add('vim-airline/vim-airline')
  call dein#add('vim-airline/vim-airline-themes')
  call dein#add('chrisbra/csv.vim')
  call dein#add('powerline/fonts', { 'build': './install.sh' })
  call dein#add('godlygeek/tabular')
  
  call dein#add('vim-ruby/vim-ruby')
  call dein#add('tpope/vim-rails')
  call dein#add('KurtPreston/vim-autoformat-rails')
  call dein#add('rking/ag.vim')

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable
set number

" Sane mappings for me.
map <c-e> :NERDTreeToggle<cr>
let g:NERDTreeWinPos = "right"

map <c-f> :FZF<cr>

map <c-l> :tabn<cr> 
map <c-h> :tabp<cr> 
map <c-n> :tabnew<cr>


autocmd User Rails let b:surround_{char2nr('-')} = "<% \r %>" " displays <% %> correctly
set cpoptions+=$ " puts a $ marker for the end of words/lines in cw/c$ commands

let g:ag_working_path_mode="r"

vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)

" Formatting, indentation and tabbing
set autoindent smartindent
set smarttab                    " Make <tab> and <backspace> smarter
set expandtab
set tabstop=2
set shiftwidth=2
set textwidth=80
set laststatus=2

" color PapayaWhip
color mayansmoke


" airline
let g:airline_theme='powerlineish'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

if exists("did_load_csvfiletype")
  finish
endif
let did_load_csvfiletype=1

augroup filetypedetect
  au! BufRead,BufNewFile *.csv,*.dat    setfiletype csv
augroup END
