call pathogen#infect('bundle/{}')
call pathogen#helptags()

syntax on
filetype plugin indent on
set number

autocmd Filetype html setlocal ts=2 sts=2 sw=2 
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2 
autocmd Filetype javascript setlocal ts=4 sts=4 sw=4

autocmd vimenter * NERDTree

set rtp+=~/.vim/bundle/fzf
